### ISSUE TITLE
Upgrade hlint to 3.x

### ISSUE THREAD

**Issue by dkubb** [mbj/devtools-hs#17]
The current version of hlint is [3.1.1](https://hackage.haskell.org/package/hlint-3.1.1), but this package restrict the version to less than 3.

It has a [number of changes and improvements](https://github.com/ndmitchell/hlint/blob/master/CHANGES.txt).

**Comment by mbj** [comment]
This was done in #20

**Comment by mbj** [comment]
@dkubb This change was also released as 0.0.2.
